# Server
server.port=2003
spring.application.name=order-service

# MySQL - Docker
spring.datasource.url=jdbc:mysql://localhost:3308/order_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Catalog Service URL
catalog.service.url=http://catalog-service:2001

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.topic.order-events=order-events

# Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=${spring.application.name}