# Server
server.port=2003
spring.application.name=order-service

# MySQL - Docker
spring.datasource.url=jdbc:mysql://localhost:3308/order_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Catalog Service URL
catalog.service.url=http://catalog-service:2001

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.topic.order-events=order-events

# Prometheus
management.endpoints.web.exposure.include=health,prometheus,circuitbreakers
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=${spring.application.name}


# ==================== CIRCUIT BREAKER - catalogService =================

# name must match @CircuitBreaker(name="catalogService") in your code
resilience4j.circuitbreaker.instances.catalogService.register-health-indicator=true

# evaluate last 5 calls to decide CB state
resilience4j.circuitbreaker.instances.catalogService.sliding-window-size=5

# need at least 3 calls before CB can open - avoids opening on very first failure
resilience4j.circuitbreaker.instances.catalogService.minimum-number-of-calls=3

# if 50% of last 5 calls fail, CB moves CLOSED -> OPEN
resilience4j.circuitbreaker.instances.catalogService.failure-rate-threshold=50

# stay OPEN for 10s, then move to HALF_OPEN to test if catalog recovered
resilience4j.circuitbreaker.instances.catalogService.wait-duration-in-open-state=10s

# in HALF_OPEN state, allow 2 probe calls to check recovery
resilience4j.circuitbreaker.instances.catalogService.permitted-number-of-calls-in-half-open-state=2


# ================== RETRY - catalogService =========================

# 3 total attempts = 1 original call + 2 retries
resilience4j.retry.instances.catalogService.max-attempts=3

# wait 1s before first retry
resilience4j.retry.instances.catalogService.wait-duration=1s

# instead of retrying at fixed 1s intervals, increase wait each time
resilience4j.retry.instances.catalogService.enable-exponential-backoff=true

# 1s -> 2s -> 4s gap between retries
resilience4j.retry.instances.catalogService.exponential-backoff-multiplier=2

# ================= TIME LIMITER - catalogService =====================

# if catalog-service doesn't respond in 3s, treat it as failure
resilience4j.timelimiter.instances.catalogService.timeout-duration=3s

# don't cancel the running future, just mark it as failed
resilience4j.timelimiter.instances.catalogService.cancel-running-future=false

# ===== CIRCUIT BREAKER HEALTH =====

# shows CB state (CLOSED/OPEN/HALF_OPEN) in /actuator/health response
management.health.circuitbreakers.enabled=true

# ======
logging.level.io.github.resilience4j.retry=DEBUG
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.io.github.resilience4j=TRACE