# --------------------
# App
# --------------------
spring.application.name=payment-service
server.port=2004

# --------------------
# Database
# --------------------
spring.datasource.url=jdbc:mysql://mysql:3306/paymentdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --------------------
# JPA
# --------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --------------------
# Kafka
# --------------------
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# --------------------
# Kafka Topic
# --------------------
payment.kafka.topic=payment-events

# --------------------
# Order Service
# --------------------
order.service.url=http://order-service:2003

# Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=${spring.application.name}