name: AWS SSM Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  EC2_INSTANCE_ID: i-0bf1e5559e77fc67

jobs:
  test-ssm:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::282477853061:role/github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Send SSM command
        id: send-command
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --region "$AWS_REGION" \
            --instance-ids "$EC2_INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["hostname"]' \
            --query "Command.CommandId" \
            --output text)

          echo "COMMAND_ID=$COMMAND_ID" >> "$GITHUB_ENV"

      - name: Wait for command result
        run: |
          aws ssm wait command-executed \
            --region "$AWS_REGION" \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID"

      - name: Get command output
        run: |
          aws ssm get-command-invocation \
            --region "$AWS_REGION" \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID"
